all: RSAPubKey RSASecKey RSATest

RSAPubKey: RSAPubKey.java
	javac RSAPubKey.java
	java RSAPubKey

RSASecKey: RSASEcKey.java
	javac RSASecKey.java
	java RSASecKey

RSATest: RSATest.java
	javac RSATest.java
	java RSATest

clean:
	rm *.class rm *.java~
