all: ElgamalPubKey ElgamalSecKey ElgamalTest

ElgamalPubKey:
	javac ElgamalPubKey.java

ElgamalSecKey:
	javac ElgamalSecKey.java

ElgamalTest:
	javac ElgamalTest.java

clean:
	rm *.java~ rm Makefile~ rm *.class